#!/bin/bash
#
# chkconfig: 35 90 12
# description: CPU 
#

# Get function from functions library

# Start the service FOO
start() {
        /usr/local/bin/devect 
}

# Restart the service FOO
stop() {
        pkill devect
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status devect
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0

